name: instagram_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  cloud_firestore: ^3.1.9
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.8
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
